id: P007096
initial_creation_type: ocr
source_metadata:
  id: bdr:W23446
  title: འཛི་སྒར་ཀོང་སྤྲུལ་གསུང་ཕྱོགས་བསྡེབས།
  author: ''
  volumes:
    88aa91304f8b4062b101dbf5581c626e:
      image_group_id: I1877
      title: ''
      volume_number: 1
      total_pages: 757
    c5f98d4e1cba436b954be70316147af3:
      image_group_id: I1878
      title: ''
      volume_number: 2
      total_pages: 709
    c451a1982a794addb2f55d0e7ec52a20:
      image_group_id: I1879
      title: ''
      volume_number: 3
      total_pages: 699
    96dc9c6c216c4e4486eac859ba217cfe:
      image_group_id: I1880
      title: ''
      volume_number: 4
      total_pages: 673
    0598cc4af0b3475889b24ab010af0a50:
      image_group_id: I1881
      title: ''
      volume_number: 5
      total_pages: 683
    5ace656ff34342eb815bb8df7fd81d99:
      image_group_id: I1882
      title: ''
      volume_number: 6
      total_pages: 663
    1058b6b4f3a94c95b71a2e866ea00984:
      image_group_id: I1883
      title: ''
      volume_number: 7
      total_pages: 654
    2f8039c9abba4ec3afd7aff1f7b36e56:
      image_group_id: I1884
      title: ''
      volume_number: 8
      total_pages: 716
    3a72daacee704fec908a949679daca26:
      image_group_id: I1885
      title: ''
      volume_number: 9
      total_pages: 735
    ec3f23fa507e46bbb25961c2296ea821:
      image_group_id: I1886
      title: ''
      volume_number: 10
      total_pages: 661
    e11d314980d44c90adc02596a810aab0:
      image_group_id: I1887
      title: ''
      volume_number: 11
      total_pages: 729
    959838f6a8c444c19c4097aaf055325e:
      image_group_id: I1888
      title: ''
      volume_number: 12
      total_pages: 687
ebook_metadata:
  title: འཛི་སྒར་ཀོང་སྤྲུལ་གསུང་ཕྱོགས་བསྡེབས།
  author: ''
  sku: P007096
  cover: cover.jpg
  layers:
  - pagination
