id: I1F46D988
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:02:31+00:00'
last_modified: '2022-06-09T04:50:21.331762+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23446
  title: འཛི་སྒར་ཀོང་སྤྲུལ་གསུང་ཕྱོགས་བསྡེབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BB44:
      image_group_id: I1877
      title: ''
      total_pages: 757
      order: 1
      base_file: BB44.txt
    5E54:
      image_group_id: I1878
      title: ''
      total_pages: 709
      order: 2
      base_file: 5E54.txt
    2C6F:
      image_group_id: I1879
      title: ''
      total_pages: 699
      order: 3
      base_file: 2C6F.txt
    '5754':
      image_group_id: I1880
      title: ''
      total_pages: 673
      order: 4
      base_file: 5754.txt
    33D5:
      image_group_id: I1881
      title: ''
      total_pages: 683
      order: 5
      base_file: 33D5.txt
    3A70:
      image_group_id: I1882
      title: ''
      total_pages: 663
      order: 6
      base_file: 3A70.txt
    '2218':
      image_group_id: I1883
      title: ''
      total_pages: 654
      order: 7
      base_file: 2218.txt
    2D5E:
      image_group_id: I1884
      title: ''
      total_pages: 716
      order: 8
      base_file: 2D5E.txt
    3A94:
      image_group_id: I1885
      title: ''
      total_pages: 735
      order: 9
      base_file: 3A94.txt
    5BBD:
      image_group_id: I1886
      title: ''
      total_pages: 661
      order: 10
      base_file: 5BBD.txt
    9AB3:
      image_group_id: I1887
      title: ''
      total_pages: 729
      order: 11
      base_file: 9AB3.txt
    58CA:
      image_group_id: I1888
      title: ''
      total_pages: 687
      order: 12
      base_file: 58CA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
