id: I1F46D988
legacy_id: P007096
ocr_import_info:
  bdrc_scan_id: W23446
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T10:00:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:04:27.826713+00:00'
last_modified: 2022-09-02 09:07:02.391219
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23446
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23446
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཛི་སྒར་ཀོང་སྤྲུལ་གསུང་ཕྱོགས་བསྡེབས།
  author: འཛི་སྒར་ཀོང་སྤྲུལ་བློ་གྲོས་རབ་འཕེལ།
statistics:
  ocr_word_mean_confidence_index: 0.8836533269048635
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1886:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1886
      total_pages: 661
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1886.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8535308594788389
    legacy_id: v010
  I1879:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1879
      total_pages: 699
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1879.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9121834876355461
    legacy_id: v003
  I1880:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1880
      total_pages: 673
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1880.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9057998124281664
    legacy_id: v004
  I1882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1882
      total_pages: 663
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1882.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8676570761563668
    legacy_id: v006
  I1881:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1881
      total_pages: 683
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1881.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8806903011000442
    legacy_id: v005
  I1877:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1877
      total_pages: 757
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1877.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9056491523946908
    legacy_id: v001
  I1878:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1878
      total_pages: 709
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1878.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8979935711600255
    legacy_id: v002
  I1883:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1883
      total_pages: 654
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1883.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8930177014403041
    legacy_id: v007
  I1887:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1887
      total_pages: 729
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1887.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8670650444613981
    legacy_id: v011
  I1884:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1884
      total_pages: 716
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1884.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8497741623736319
    legacy_id: v008
  I1888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1888
      total_pages: 687
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1888.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8636878991008988
    legacy_id: v012
  I1885:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1885
      total_pages: 735
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1885.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8504860802770614
    legacy_id: v009
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
